[package]
name = "edge-proxy"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1.5"
env_logger = "0.6.2"
log = "0.4.7"

